/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package net.is.lms.project.frames;

import javax.swing.*;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.util.Objects;

import net.is.lms.project.instances.User;

/**
 * @author dadi
 */
public class LoginWindow extends javax.swing.JFrame {
    private final FetchObjects objects = new FetchObjects();
    private boolean standardViewValue = false;
    private Runnable callback;

    /**
     * Creates new form LoginWindow
     */
    public LoginWindow() {
        createFrame();
    }

    // Führt StandardView Methode aus, um die View bei Erfolg zu disposen
    public LoginWindow(boolean standardViewValue, Runnable callback) {
        this.callback = callback;
        this.standardViewValue = standardViewValue;

        createFrame();
    }

    private void createFrame() {
        setNimbusLook();
        initComponents();

        objects.updateUserList();
        extendComponents();

        setResizable(false);
        setLocationRelativeTo(null);
        setTitle("Login");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1MainLogin = new javax.swing.JPanel();
        jLabel1LoginTitle = new javax.swing.JLabel();
        jButton1SaveLogin = new javax.swing.JButton();
        jButton2CancelLogin = new javax.swing.JButton();
        jPanel2LoginSubPanel = new javax.swing.JPanel();
        jTextField1UsernameLogin = new javax.swing.JTextField();
        jPasswordField1Login = new javax.swing.JPasswordField();
        jLabel2IconUsernameLogin = new javax.swing.JLabel();
        jLabel3IconPasswordLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1MainLogin.setBackground(new java.awt.Color(203, 230, 255));

        jLabel1LoginTitle.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1LoginTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1LoginTitle.setText("Login");

        jButton1SaveLogin.setText("Save");
        jButton1SaveLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1SaveLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1SaveLoginActionPerformed(evt);
            }
        });

        jButton2CancelLogin.setText("Cancel");
        jButton2CancelLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2CancelLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2CancelLoginActionPerformed(evt);
            }
        });

        jPanel2LoginSubPanel.setBackground(new java.awt.Color(203, 230, 255));

        jTextField1UsernameLogin.setText("Username");

        jPasswordField1Login.setText("Password");
        jPasswordField1Login.setToolTipText("");

        jLabel2IconUsernameLogin.setText("jLabel2");

        jLabel3IconPasswordLogin.setText("jLabel2");

        javax.swing.GroupLayout jPanel2LoginSubPanelLayout = new javax.swing.GroupLayout(jPanel2LoginSubPanel);
        jPanel2LoginSubPanel.setLayout(jPanel2LoginSubPanelLayout);
        jPanel2LoginSubPanelLayout.setHorizontalGroup(
                jPanel2LoginSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2LoginSubPanelLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel2LoginSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel2IconUsernameLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3IconPasswordLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2LoginSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField1UsernameLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                        .addComponent(jPasswordField1Login))
                                .addGap(18, 18, 18))
        );
        jPanel2LoginSubPanelLayout.setVerticalGroup(
                jPanel2LoginSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2LoginSubPanelLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel2LoginSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextField1UsernameLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2IconUsernameLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(50, 50, 50)
                                .addGroup(jPanel2LoginSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jPasswordField1Login, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3IconPasswordLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout jPanel1MainLoginLayout = new javax.swing.GroupLayout(jPanel1MainLogin);
        jPanel1MainLogin.setLayout(jPanel1MainLoginLayout);
        jPanel1MainLoginLayout.setHorizontalGroup(
                jPanel1MainLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1MainLoginLayout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(jPanel2LoginSubPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(53, 53, 53))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1MainLoginLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jButton1SaveLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2CancelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1MainLoginLayout.createSequentialGroup()
                                .addContainerGap(30, Short.MAX_VALUE)
                                .addComponent(jLabel1LoginTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1MainLoginLayout.setVerticalGroup(
                jPanel1MainLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1MainLoginLayout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jLabel1LoginTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 61, Short.MAX_VALUE)
                                .addGap(66, 66, 66)
                                .addComponent(jPanel2LoginSubPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(60, 60, 60)
                                .addGroup(jPanel1MainLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton2CancelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton1SaveLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1MainLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1MainLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Login Save Button
    private void jButton1SaveLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1SaveLoginActionPerformed
        try {
            if (checkCredentials(jTextField1UsernameLogin.getText(), jPasswordField1Login.getText())) {
                this.dispose();
                callback.run(); // Schließt Standardview
                new UserView(jTextField1UsernameLogin.getText()).setVisible(true);
            } else if (jTextField1UsernameLogin.getText().equals("Admin") && jPasswordField1Login.getText().equals("1234")) {
                this.dispose();
                callback.run(); // Schließt Standardview
                new AdminView().setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Login not successful!", "Error!", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Unexpected error, please try again", "Error", JOptionPane.ERROR_MESSAGE);
            System.out.println("Error whilst clicking saveLoginButton: " + ex.getMessage());
        }
    }//GEN-LAST:event_jButton1SaveLoginActionPerformed

    // Login Cancel Button
    private void jButton2CancelLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2CancelLoginActionPerformed
        if (standardViewValue) StandardView.jButton1LoginSV.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_jButton2CancelLoginActionPerformed

    private boolean checkCredentials(String username, String password) {
        // Todo username sollte keine groß/kleinschreibung beachten
        for (User user : objects.getUsers()) {
//            System.out.println("username: " + user.getUsername() + " / password: " + user.getPassword());
            if (user.getUsername().equals(username)) {
                if (user.getPassword().equals(password)) {
                    return true;
                }
            }
        }
        return false;
    }


    private void extendComponents() {
        // Username wenn leerer Input
        jTextField1UsernameLogin.addFocusListener(new FocusAdapter() {
            public void focusGained(FocusEvent e) {
                if (jTextField1UsernameLogin.getText().equals("Username")) {
                    jTextField1UsernameLogin.setText("");
                }
            }

            public void focusLost(FocusEvent e) {
                if (jTextField1UsernameLogin.getText().isEmpty()) {
                    jTextField1UsernameLogin.setText("Username");
                }
            }
        });

        // Password (bzw ****) wenn leerer Input
        jPasswordField1Login.addFocusListener(new FocusAdapter() {
            public void focusGained(FocusEvent e) {
                if (jPasswordField1Login.getText().equals("Password")) {
                    jPasswordField1Login.setText("");
                }
            }

            public void focusLost(FocusEvent e) {
                if (jPasswordField1Login.getText().isEmpty()) {
                    jPasswordField1Login.setText("Password");
                }
            }
        });

        jLabel2IconUsernameLogin.setIcon(new javax.swing.ImageIcon(Objects.requireNonNull(getClass().getResource("/icons/LoginUsernameIcon.png"))));
        jLabel3IconPasswordLogin.setIcon(new javax.swing.ImageIcon(Objects.requireNonNull(getClass().getResource("/icons/LoginPasswordIcon.png"))));

    }

    private void setNimbusLook() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException |
                 UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1SaveLogin;
    private javax.swing.JButton jButton2CancelLogin;
    private javax.swing.JLabel jLabel1LoginTitle;
    private javax.swing.JLabel jLabel2IconUsernameLogin;
    private javax.swing.JLabel jLabel3IconPasswordLogin;
    private javax.swing.JPanel jPanel1MainLogin;
    private javax.swing.JPanel jPanel2LoginSubPanel;
    private javax.swing.JPasswordField jPasswordField1Login;
    private javax.swing.JTextField jTextField1UsernameLogin;
    // End of variables declaration//GEN-END:variables
}
