/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package net.is.lms.project.frames;

import net.is.lms.project.instances.Book;
import net.is.lms.project.utilities.Analytics;
import net.is.lms.project.utilities.CellRenderer;
import net.is.lms.project.utilities.ImageRenderer;

import javax.swing.*;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import java.util.Objects;

/**
 * @author dadi
 */
public class StandardView extends javax.swing.JFrame {
    private final Analytics analytics = new Analytics("Standard");
    private final FetchObjects objects = new FetchObjects();

    /**
     * Creates new form StandardView
     */
    public StandardView() {
        setNimbusLook();
        initComponents();
        addIcons();
        setTitle("Library Management System (1.2)");
        setExtendedState(JFrame.MAXIMIZED_BOTH); // maximiert Frame am Start
        setLocationRelativeTo(null);

        setTableModels();
        updateStatistics();
        addTableListener();
        updateBookOverviewAV();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1MenubarSV = new javax.swing.JPanel();
        jPanel2TitleBlockSV = new javax.swing.JPanel();
        jLabel1TitleSV = new javax.swing.JLabel();
        jLabel2IconSV = new javax.swing.JLabel();
        jLabel3SubtitleSV = new javax.swing.JLabel();
        jButton1LoginSV = new javax.swing.JButton();
        jPanel3MainframeSV = new javax.swing.JPanel();
        jPanel4BooksOverviewSV = new javax.swing.JPanel();
        jLabel4TitleBooksOverviewSV = new javax.swing.JLabel();
        jPanel5AllBooksSV = new javax.swing.JPanel();
        jLabel5AllBooksTitleSV = new javax.swing.JLabel();
        jLabel6AllBooksSubtitleSV = new javax.swing.JLabel();
        jPanel6AvBooksSV = new javax.swing.JPanel();
        jLabel7AvBooksTitleSV = new javax.swing.JLabel();
        jLabel8AvBooksSubtitleSV = new javax.swing.JLabel();
        jPanel7YourBowBooksSV = new javax.swing.JPanel();
        jLabel9YourBowBooksTitleSV = new javax.swing.JLabel();
        jLabel10YourBowBooksSubtitleSV = new javax.swing.JLabel();
        jPanel9BooksOverviewTableSV = new javax.swing.JPanel();
        jLabel11SearchSV = new javax.swing.JLabel();
        jTextField1BooksOverviewSearchSV = new javax.swing.JTextField();
        jScrollPaneBooksOverviewSV = new javax.swing.JScrollPane();
        jTable1BooksOverViewSV = new javax.swing.JTable() {
            public boolean editCellAt(int row, int column, java.util.EventObject e) {
                return false;
            }
        };

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1MenubarSV.setBackground(new java.awt.Color(122, 173, 210));
        jPanel1MenubarSV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel2TitleBlockSV.setBackground(new java.awt.Color(65, 123, 165));
        jPanel2TitleBlockSV.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel2TitleBlockSV.setPreferredSize(new java.awt.Dimension(280, 114));
        jPanel2TitleBlockSV.setRequestFocusEnabled(false);

        jLabel1TitleSV.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1TitleSV.setText("Library Management");

        jLabel2IconSV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel3SubtitleSV.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3SubtitleSV.setText("not logged in");

        javax.swing.GroupLayout jPanel2TitleBlockSVLayout = new javax.swing.GroupLayout(jPanel2TitleBlockSV);
        jPanel2TitleBlockSV.setLayout(jPanel2TitleBlockSVLayout);
        jPanel2TitleBlockSVLayout.setHorizontalGroup(
                jPanel2TitleBlockSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2TitleBlockSVLayout.createSequentialGroup()
                                .addGroup(jPanel2TitleBlockSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2TitleBlockSVLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jLabel2IconSV, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel1TitleSV))
                                        .addGroup(jPanel2TitleBlockSVLayout.createSequentialGroup()
                                                .addGap(103, 103, 103)
                                                .addComponent(jLabel3SubtitleSV)))
                                .addContainerGap(8, Short.MAX_VALUE))
        );
        jPanel2TitleBlockSVLayout.setVerticalGroup(
                jPanel2TitleBlockSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2TitleBlockSVLayout.createSequentialGroup()
                                .addGroup(jPanel2TitleBlockSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2TitleBlockSVLayout.createSequentialGroup()
                                                .addGap(15, 15, 15)
                                                .addComponent(jLabel1TitleSV))
                                        .addGroup(jPanel2TitleBlockSVLayout.createSequentialGroup()
                                                .addGap(3, 3, 3)
                                                .addComponent(jLabel2IconSV, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(12, 12, 12)
                                .addComponent(jLabel3SubtitleSV)
                                .addContainerGap(15, Short.MAX_VALUE))
        );

        jButton1LoginSV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1LoginSV.setText("Login");
        jButton1LoginSV.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1LoginSV.setPreferredSize(new java.awt.Dimension(147, 33));
        jButton1LoginSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1LoginSVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1MenubarSVLayout = new javax.swing.GroupLayout(jPanel1MenubarSV);
        jPanel1MenubarSV.setLayout(jPanel1MenubarSVLayout);
        jPanel1MenubarSVLayout.setHorizontalGroup(
                jPanel1MenubarSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2TitleBlockSV, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                        .addGroup(jPanel1MenubarSVLayout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(jButton1LoginSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1MenubarSVLayout.setVerticalGroup(
                jPanel1MenubarSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1MenubarSVLayout.createSequentialGroup()
                                .addComponent(jPanel2TitleBlockSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jButton1LoginSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 620, Short.MAX_VALUE))
        );

        jLabel4TitleBooksOverviewSV.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel4TitleBooksOverviewSV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4TitleBooksOverviewSV.setText("Books Overview");

        jPanel5AllBooksSV.setBackground(new java.awt.Color(78, 170, 70));
        jPanel5AllBooksSV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5AllBooksSV.setMinimumSize(new java.awt.Dimension(121, 134));
        jPanel5AllBooksSV.setPreferredSize(new java.awt.Dimension(134, 134));
        jPanel5AllBooksSV.setRequestFocusEnabled(false);

        jLabel5AllBooksTitleSV.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5AllBooksTitleSV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5AllBooksTitleSV.setText("<html><div align=\"center\">All books</div></html>");
        jLabel5AllBooksTitleSV.setPreferredSize(new java.awt.Dimension(122, 22));

        jLabel6AllBooksSubtitleSV.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6AllBooksSubtitleSV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6AllBooksSubtitleSV.setText("0");

        javax.swing.GroupLayout jPanel5AllBooksSVLayout = new javax.swing.GroupLayout(jPanel5AllBooksSV);
        jPanel5AllBooksSV.setLayout(jPanel5AllBooksSVLayout);
        jPanel5AllBooksSVLayout.setHorizontalGroup(
                jPanel5AllBooksSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5AllBooksSVLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel5AllBooksSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6AllBooksSubtitleSV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5AllBooksTitleSV, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
                                .addContainerGap())
        );
        jPanel5AllBooksSVLayout.setVerticalGroup(
                jPanel5AllBooksSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5AllBooksSVLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel5AllBooksTitleSV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(31, 31, 31)
                                .addComponent(jLabel6AllBooksSubtitleSV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(30, 30, 30))
        );

        jPanel6AvBooksSV.setBackground(new java.awt.Color(245, 158, 30));
        jPanel6AvBooksSV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6AvBooksSV.setMinimumSize(new java.awt.Dimension(121, 134));
        jPanel6AvBooksSV.setPreferredSize(new java.awt.Dimension(134, 134));
        jPanel6AvBooksSV.setRequestFocusEnabled(false);

        jLabel7AvBooksTitleSV.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel7AvBooksTitleSV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7AvBooksTitleSV.setText("<html><div align=\"center\">Available Books</div></html>");
        jLabel7AvBooksTitleSV.setMaximumSize(new java.awt.Dimension(122, 44));
        jLabel7AvBooksTitleSV.setMinimumSize(new java.awt.Dimension(74, 44));
        jLabel7AvBooksTitleSV.setPreferredSize(new java.awt.Dimension(114, 44));

        jLabel8AvBooksSubtitleSV.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8AvBooksSubtitleSV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8AvBooksSubtitleSV.setText("0");

        javax.swing.GroupLayout jPanel6AvBooksSVLayout = new javax.swing.GroupLayout(jPanel6AvBooksSV);
        jPanel6AvBooksSV.setLayout(jPanel6AvBooksSVLayout);
        jPanel6AvBooksSVLayout.setHorizontalGroup(
                jPanel6AvBooksSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6AvBooksSVLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel6AvBooksSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7AvBooksTitleSV, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                        .addComponent(jLabel8AvBooksSubtitleSV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        jPanel6AvBooksSVLayout.setVerticalGroup(
                jPanel6AvBooksSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6AvBooksSVLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel7AvBooksTitleSV, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8AvBooksSubtitleSV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(32, 32, 32))
        );

        jPanel7YourBowBooksSV.setBackground(new java.awt.Color(101, 180, 255));
        jPanel7YourBowBooksSV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7YourBowBooksSV.setMinimumSize(new java.awt.Dimension(121, 134));
        jPanel7YourBowBooksSV.setPreferredSize(new java.awt.Dimension(134, 134));
        jPanel7YourBowBooksSV.setRequestFocusEnabled(false);

        jLabel9YourBowBooksTitleSV.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel9YourBowBooksTitleSV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9YourBowBooksTitleSV.setText("<html><div align=\"center\">Your borrowed<br>books</div></html>");
        jLabel9YourBowBooksTitleSV.setToolTipText("");

        jLabel10YourBowBooksSubtitleSV.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel10YourBowBooksSubtitleSV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10YourBowBooksSubtitleSV.setText("Log in to view");

        javax.swing.GroupLayout jPanel7YourBowBooksSVLayout = new javax.swing.GroupLayout(jPanel7YourBowBooksSV);
        jPanel7YourBowBooksSV.setLayout(jPanel7YourBowBooksSVLayout);
        jPanel7YourBowBooksSVLayout.setHorizontalGroup(
                jPanel7YourBowBooksSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7YourBowBooksSVLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(jPanel7YourBowBooksSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9YourBowBooksTitleSV, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                                        .addComponent(jLabel10YourBowBooksSubtitleSV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        jPanel7YourBowBooksSVLayout.setVerticalGroup(
                jPanel7YourBowBooksSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7YourBowBooksSVLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9YourBowBooksTitleSV)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10YourBowBooksSubtitleSV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout jPanel4BooksOverviewSVLayout = new javax.swing.GroupLayout(jPanel4BooksOverviewSV);
        jPanel4BooksOverviewSV.setLayout(jPanel4BooksOverviewSVLayout);
        jPanel4BooksOverviewSVLayout.setHorizontalGroup(
                jPanel4BooksOverviewSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4BooksOverviewSVLayout.createSequentialGroup()
                                .addContainerGap(258, Short.MAX_VALUE)
                                .addComponent(jPanel5AllBooksSV, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                                .addComponent(jPanel6AvBooksSV, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                                .addComponent(jPanel7YourBowBooksSV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap(259, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4BooksOverviewSVLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4TitleBooksOverviewSV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4BooksOverviewSVLayout.setVerticalGroup(
                jPanel4BooksOverviewSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4BooksOverviewSVLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel4TitleBooksOverviewSV)
                                .addGap(30, 30, 30)
                                .addGroup(jPanel4BooksOverviewSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jPanel5AllBooksSV, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                        .addComponent(jPanel6AvBooksSV, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                        .addComponent(jPanel7YourBowBooksSV, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                                .addGap(43, 43, 43))
        );

        jLabel11SearchSV.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11SearchSV.setText("Search:");

        jTable1BooksOverViewSV.setModel(new javax.swing.table.DefaultTableModel());
        jScrollPaneBooksOverviewSV.setViewportView(jTable1BooksOverViewSV);

        javax.swing.GroupLayout jPanel9BooksOverviewTableSVLayout = new javax.swing.GroupLayout(jPanel9BooksOverviewTableSV);
        jPanel9BooksOverviewTableSV.setLayout(jPanel9BooksOverviewTableSVLayout);
        jPanel9BooksOverviewTableSVLayout.setHorizontalGroup(
                jPanel9BooksOverviewTableSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9BooksOverviewTableSVLayout.createSequentialGroup()
                                .addContainerGap(100, Short.MAX_VALUE)
                                .addGroup(jPanel9BooksOverviewTableSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jScrollPaneBooksOverviewSV)
                                        .addGroup(jPanel9BooksOverviewTableSVLayout.createSequentialGroup()
                                                .addComponent(jLabel11SearchSV)
                                                .addGap(46, 46, 46)
                                                .addComponent(jTextField1BooksOverviewSearchSV, javax.swing.GroupLayout.DEFAULT_SIZE, 825, Short.MAX_VALUE)))
                                .addContainerGap(100, Short.MAX_VALUE))
        );
        jPanel9BooksOverviewTableSVLayout.setVerticalGroup(
                jPanel9BooksOverviewTableSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel9BooksOverviewTableSVLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(jPanel9BooksOverviewTableSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextField1BooksOverviewSearchSV, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel11SearchSV))
                                .addGap(33, 33, 33)
                                .addComponent(jScrollPaneBooksOverviewSV, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3MainframeSVLayout = new javax.swing.GroupLayout(jPanel3MainframeSV);
        jPanel3MainframeSV.setLayout(jPanel3MainframeSVLayout);
        jPanel3MainframeSVLayout.setHorizontalGroup(
                jPanel3MainframeSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel4BooksOverviewSV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel9BooksOverviewTableSV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3MainframeSVLayout.setVerticalGroup(
                jPanel3MainframeSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3MainframeSVLayout.createSequentialGroup()
                                .addComponent(jPanel4BooksOverviewSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel9BooksOverviewTableSV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1MenubarSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jPanel3MainframeSV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1MenubarSV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3MainframeSV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1LoginSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1LoginSVActionPerformed
        jButton1LoginSV.setEnabled(false); // Deaktiviert Login Button (kann auch als Dialog implementiert werden)
        jTable1BooksOverViewSV.getSelectionModel().clearSelection();
        new LoginWindow(true, this::disposeFrame).setVisible(true); // übergibt CloseFrame Methode, damit Standardview geschlossen werden kann
    }//GEN-LAST:event_jButton1LoginSVActionPerformed

    private void addIcons() {
        jLabel2IconSV.setIcon(new javax.swing.ImageIcon(Objects.requireNonNull(getClass().getResource("/icons/LmsIcon.png"))));
    }

    protected void disposeFrame() {
        this.dispose();
    }

    private void setNimbusLook() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException |
                 UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StandardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }


    private void setTableModels() {
        jTable1BooksOverViewSV.setAutoCreateRowSorter(true);

        jTable1BooksOverViewSV.setRowHeight(60);

        jTable1BooksOverViewSV.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        // Layout Werte
        String[] bookColumnNames = {"Cover", "Title", "Author", "Pages", "ISBN", "Location", "Availability"};

        jTable1BooksOverViewSV.setModel(new javax.swing.table.DefaultTableModel(bookColumnNames, 0));

        // Layout der Tabellen
        // Todo in eigene Klasse und dann checken von welcher Klasse die neue aufgerufen wird
        TableCellRenderer originalRenderer = jTable1BooksOverViewSV.getDefaultRenderer(Object.class);
        jTable1BooksOverViewSV.setDefaultRenderer(Object.class, new CellRenderer(originalRenderer));
        jTable1BooksOverViewSV.getColumnModel().getColumn(0).setCellRenderer(new ImageRenderer()); // Implementiert Book Cover
    }

    private void updateStatistics() {
        analytics.getAnalytics("");
        jLabel6AllBooksSubtitleSV.setText(Integer.toString(analytics.getBookAmount()));
        jLabel8AvBooksSubtitleSV.setText(Integer.toString(analytics.getAvailableBooks()));
    }

    private void updateBookOverviewAV() {
        objects.updateBookList();

        DefaultTableModel modelBookOverview = (DefaultTableModel) jTable1BooksOverViewSV.getModel();
        modelBookOverview.setRowCount(0);

        for (Book book : objects.getBooks()) {
            String cover = book.getCoverLocation();
            String title = book.getTitle();
            String author = book.getAuthor();
            String pages = book.getPages();
            String isbn = book.getIsbn();
            String location = book.getLocation();
            String availability = book.getAvailability();

            Object[] data = {cover, title, author, pages, isbn, location, availability};
            modelBookOverview.addRow(data);
        }
    }

    private void addTableListener() {
        jTextField1BooksOverviewSearchSV.getDocument().addDocumentListener(
                new DocumentListener() {
                    @Override
                    public void insertUpdate(DocumentEvent e) {
                        searchBooksOverviewTable(jTextField1BooksOverviewSearchSV.getText());
                    }

                    @Override
                    public void removeUpdate(DocumentEvent e) {
                        searchBooksOverviewTable(jTextField1BooksOverviewSearchSV.getText());
                    }

                    @Override
                    public void changedUpdate(DocumentEvent e) {
                        searchBooksOverviewTable(jTextField1BooksOverviewSearchSV.getText());
                    }
                }
        );
    }

    private void searchBooksOverviewTable(String input) {
        DefaultTableModel currTableModelBooksOverview = (DefaultTableModel) jTable1BooksOverViewSV.getModel();
        currTableModelBooksOverview.setRowCount(0); // Table wird geleert

        for (Book book : objects.getBooks()) {
            String cover = book.getCoverLocation();
            String title = book.getTitle();
            String author = book.getAuthor();
            String pages = book.getPages();
            String isbn = book.getIsbn();
            String location = book.getLocation();
            String availability = book.getAvailability();

            if (title.contains(input) || author.contains(input) || pages.contains(input) || isbn.contains(input) || location.contains(input)) {
                Object[] row = {cover, title, author, pages, isbn, location, availability};
                currTableModelBooksOverview.addRow(row);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected static javax.swing.JButton jButton1LoginSV;
    private javax.swing.JLabel jLabel10YourBowBooksSubtitleSV;
    private javax.swing.JLabel jLabel11SearchSV;
    private javax.swing.JLabel jLabel1TitleSV;
    private javax.swing.JLabel jLabel2IconSV;
    private javax.swing.JLabel jLabel3SubtitleSV;
    private javax.swing.JLabel jLabel4TitleBooksOverviewSV;
    private javax.swing.JLabel jLabel5AllBooksTitleSV;
    private javax.swing.JLabel jLabel6AllBooksSubtitleSV;
    private javax.swing.JLabel jLabel7AvBooksTitleSV;
    private javax.swing.JLabel jLabel8AvBooksSubtitleSV;
    private javax.swing.JLabel jLabel9YourBowBooksTitleSV;
    private javax.swing.JPanel jPanel1MenubarSV;
    private javax.swing.JPanel jPanel2TitleBlockSV;
    private javax.swing.JPanel jPanel3MainframeSV;
    private javax.swing.JPanel jPanel4BooksOverviewSV;
    private javax.swing.JPanel jPanel5AllBooksSV;
    private javax.swing.JPanel jPanel6AvBooksSV;
    private javax.swing.JPanel jPanel7YourBowBooksSV;
    private javax.swing.JPanel jPanel9BooksOverviewTableSV;
    private javax.swing.JScrollPane jScrollPaneBooksOverviewSV;
    private javax.swing.JTable jTable1BooksOverViewSV;
    private javax.swing.JTextField jTextField1BooksOverviewSearchSV;
    // End of variables declaration//GEN-END:variables
}
