/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package net.is.lms.project.frames;

import net.is.lms.project.instances.Book;
import net.is.lms.project.instances.BorrowedBooks;
import net.is.lms.project.utilities.Analytics;
import net.is.lms.project.utilities.CellRenderer;
import net.is.lms.project.utilities.CellRendererReturnBooks;
import net.is.lms.project.utilities.ImageRenderer;

import javax.swing.*;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import java.util.Objects;

/**
 * @author dadi
 */
public class UserView extends javax.swing.JFrame {
    private final Analytics analytics = new Analytics("User");
    private final FetchObjects objects = new FetchObjects();


    /**
     * Creates new form UserView
     */
    public UserView(String username) {
        addNimbusLook();
        initComponents();
        jPanel3MainBooksOverviewUV.setVisible(true);
        jPanel9MainYourBowBooksUV.setVisible(false);

        setExtendedState(JFrame.MAXIMIZED_BOTH); // maximiert Frame am Start
        setLocationRelativeTo(null);
        setTitle("Library Management System - User");
        addIcons();

        jLabel3SubtitleUV.setText(username);

        setTableModels();
        updateStatistics();
        addTableListener();
        updateBookOverviewAV();
        updateReturnBooksAV();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1MenubarUV = new javax.swing.JPanel();
        jPanel2TitleBlockUV = new javax.swing.JPanel();
        jLabel1TitleUV = new javax.swing.JLabel();
        jLabel2IconUV = new javax.swing.JLabel();
        jLabel3SubtitleUV = new javax.swing.JLabel();
        jButton1BookOverviewUV = new javax.swing.JButton();
        jButton2BorrowBooksUV = new javax.swing.JButton();
        jButton3LogoutUV = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel3MainBooksOverviewUV = new javax.swing.JPanel();
        jPanel4BooksOverviewUV = new javax.swing.JPanel();
        jLabel4TitleBooksOverviewUV = new javax.swing.JLabel();
        jPanel5AllBooksUV = new javax.swing.JPanel();
        jLabel5AllBooksTitleUV = new javax.swing.JLabel();
        jLabel6AllBooksSubtitleUV = new javax.swing.JLabel();
        jPanel6AvBooksUV = new javax.swing.JPanel();
        jLabel7AvBooksTitleUV = new javax.swing.JLabel();
        jLabel8AvBooksSubtitleUV = new javax.swing.JLabel();
        jPanel7YourBowBooksUV = new javax.swing.JPanel();
        jLabel9YourBowBooksTitleUV = new javax.swing.JLabel();
        jLabel10YourBowBooksSubtitleUV = new javax.swing.JLabel();
        jPanel8BooksOverviewTableUV = new javax.swing.JPanel();
        jLabel11SearchUV = new javax.swing.JLabel();
        jTextField1BooksOverviewSearchUV = new javax.swing.JTextField();
        jScrollPaneBooksOverviewUV = new javax.swing.JScrollPane();
        jTable1BooksOverviewUV = new javax.swing.JTable() {
            public boolean editCellAt(int row, int column, java.util.EventObject e) {
                return false;
            }
        };
        jPanel9MainYourBowBooksUV = new javax.swing.JPanel();
        jLabel12TitleYourBowBooksUV = new javax.swing.JLabel();
        jPanel10YourBowBooksTableUV = new javax.swing.JPanel();
        jLabel13SearchUV = new javax.swing.JLabel();
        jTextField2YourBowBooksSearchUV = new javax.swing.JTextField();
        jScrollPaneYourBowBooksUV = new javax.swing.JScrollPane();
        jTable2YourBowBooksUV = new javax.swing.JTable() {
            public boolean editCellAt(int row, int column, java.util.EventObject e) {
                return false;
            }
        };

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1MenubarUV.setBackground(new java.awt.Color(122, 173, 210));
        jPanel1MenubarUV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel2TitleBlockUV.setBackground(new java.awt.Color(65, 123, 165));
        jPanel2TitleBlockUV.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel2TitleBlockUV.setPreferredSize(new java.awt.Dimension(280, 114));
        jPanel2TitleBlockUV.setRequestFocusEnabled(false);

        jLabel1TitleUV.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1TitleUV.setText("Library Management");

        jLabel2IconUV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel3SubtitleUV.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3SubtitleUV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3SubtitleUV.setText("<Username>");
        jLabel3SubtitleUV.setToolTipText("");

        javax.swing.GroupLayout jPanel2TitleBlockUVLayout = new javax.swing.GroupLayout(jPanel2TitleBlockUV);
        jPanel2TitleBlockUV.setLayout(jPanel2TitleBlockUVLayout);
        jPanel2TitleBlockUVLayout.setHorizontalGroup(
                jPanel2TitleBlockUVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2TitleBlockUVLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2IconUV, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1TitleUV)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2TitleBlockUVLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3SubtitleUV, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(95, 95, 95))
        );
        jPanel2TitleBlockUVLayout.setVerticalGroup(
                jPanel2TitleBlockUVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2TitleBlockUVLayout.createSequentialGroup()
                                .addGroup(jPanel2TitleBlockUVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2TitleBlockUVLayout.createSequentialGroup()
                                                .addGap(15, 15, 15)
                                                .addComponent(jLabel1TitleUV))
                                        .addGroup(jPanel2TitleBlockUVLayout.createSequentialGroup()
                                                .addGap(3, 3, 3)
                                                .addComponent(jLabel2IconUV, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(12, 12, 12)
                                .addComponent(jLabel3SubtitleUV)
                                .addContainerGap(15, Short.MAX_VALUE))
        );

        jButton1BookOverviewUV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1BookOverviewUV.setText("Books Overview");
        jButton1BookOverviewUV.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1BookOverviewUV.setPreferredSize(new java.awt.Dimension(147, 33));
        jButton1BookOverviewUV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1BookOverviewUVActionPerformed(evt);
            }
        });

        jButton2BorrowBooksUV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2BorrowBooksUV.setText("Borrowed Books");
        jButton2BorrowBooksUV.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2BorrowBooksUV.setPreferredSize(new java.awt.Dimension(147, 33));
        jButton2BorrowBooksUV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2BorrowBooksUVActionPerformed(evt);
            }
        });

        jButton3LogoutUV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton3LogoutUV.setText("Logout");
        jButton3LogoutUV.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3LogoutUV.setPreferredSize(new java.awt.Dimension(147, 33));
        jButton3LogoutUV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3LogoutUVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1MenubarUVLayout = new javax.swing.GroupLayout(jPanel1MenubarUV);
        jPanel1MenubarUV.setLayout(jPanel1MenubarUVLayout);
        jPanel1MenubarUVLayout.setHorizontalGroup(
                jPanel1MenubarUVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2TitleBlockUV, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                        .addGroup(jPanel1MenubarUVLayout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addGroup(jPanel1MenubarUVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton2BorrowBooksUV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton3LogoutUV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton1BookOverviewUV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1MenubarUVLayout.setVerticalGroup(
                jPanel1MenubarUVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1MenubarUVLayout.createSequentialGroup()
                                .addComponent(jPanel2TitleBlockUV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jButton1BookOverviewUV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(jButton2BorrowBooksUV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3LogoutUV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37))
        );

        jLabel4TitleBooksOverviewUV.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel4TitleBooksOverviewUV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4TitleBooksOverviewUV.setText("Books Overview");

        jPanel5AllBooksUV.setBackground(new java.awt.Color(78, 170, 70));
        jPanel5AllBooksUV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5AllBooksUV.setMinimumSize(new java.awt.Dimension(121, 134));
        jPanel5AllBooksUV.setPreferredSize(new java.awt.Dimension(134, 134));
        jPanel5AllBooksUV.setRequestFocusEnabled(false);

        jLabel5AllBooksTitleUV.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5AllBooksTitleUV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5AllBooksTitleUV.setText("<html><div align=\"center\">All books</div></html>");
        jLabel5AllBooksTitleUV.setPreferredSize(new java.awt.Dimension(122, 22));

        jLabel6AllBooksSubtitleUV.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6AllBooksSubtitleUV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6AllBooksSubtitleUV.setText("0");

        javax.swing.GroupLayout jPanel5AllBooksUVLayout = new javax.swing.GroupLayout(jPanel5AllBooksUV);
        jPanel5AllBooksUV.setLayout(jPanel5AllBooksUVLayout);
        jPanel5AllBooksUVLayout.setHorizontalGroup(
                jPanel5AllBooksUVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5AllBooksUVLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel5AllBooksUVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6AllBooksSubtitleUV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5AllBooksTitleUV, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))
                                .addContainerGap())
        );
        jPanel5AllBooksUVLayout.setVerticalGroup(
                jPanel5AllBooksUVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5AllBooksUVLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel5AllBooksTitleUV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(31, 31, 31)
                                .addComponent(jLabel6AllBooksSubtitleUV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(30, 30, 30))
        );

        jPanel6AvBooksUV.setBackground(new java.awt.Color(245, 158, 30));
        jPanel6AvBooksUV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6AvBooksUV.setMinimumSize(new java.awt.Dimension(121, 134));
        jPanel6AvBooksUV.setPreferredSize(new java.awt.Dimension(134, 134));
        jPanel6AvBooksUV.setRequestFocusEnabled(false);

        jLabel7AvBooksTitleUV.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel7AvBooksTitleUV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7AvBooksTitleUV.setText("<html><div align=\"center\">Available Books</div></html>");
        jLabel7AvBooksTitleUV.setMaximumSize(new java.awt.Dimension(122, 44));
        jLabel7AvBooksTitleUV.setMinimumSize(new java.awt.Dimension(74, 44));
        jLabel7AvBooksTitleUV.setPreferredSize(new java.awt.Dimension(114, 44));

        jLabel8AvBooksSubtitleUV.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8AvBooksSubtitleUV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8AvBooksSubtitleUV.setText("0");

        javax.swing.GroupLayout jPanel6AvBooksUVLayout = new javax.swing.GroupLayout(jPanel6AvBooksUV);
        jPanel6AvBooksUV.setLayout(jPanel6AvBooksUVLayout);
        jPanel6AvBooksUVLayout.setHorizontalGroup(
                jPanel6AvBooksUVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6AvBooksUVLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel6AvBooksUVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7AvBooksTitleUV, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                        .addComponent(jLabel8AvBooksSubtitleUV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        jPanel6AvBooksUVLayout.setVerticalGroup(
                jPanel6AvBooksUVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6AvBooksUVLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel7AvBooksTitleUV, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8AvBooksSubtitleUV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(32, 32, 32))
        );

        jPanel7YourBowBooksUV.setBackground(new java.awt.Color(101, 180, 255));
        jPanel7YourBowBooksUV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7YourBowBooksUV.setMinimumSize(new java.awt.Dimension(121, 134));
        jPanel7YourBowBooksUV.setPreferredSize(new java.awt.Dimension(134, 134));
        jPanel7YourBowBooksUV.setRequestFocusEnabled(false);

        jLabel9YourBowBooksTitleUV.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel9YourBowBooksTitleUV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9YourBowBooksTitleUV.setText("<html><div align=\"center\">Your borrowed<br>books</div></html>");
        jLabel9YourBowBooksTitleUV.setToolTipText("");

        jLabel10YourBowBooksSubtitleUV.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10YourBowBooksSubtitleUV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10YourBowBooksSubtitleUV.setText("0");

        javax.swing.GroupLayout jPanel7YourBowBooksUVLayout = new javax.swing.GroupLayout(jPanel7YourBowBooksUV);
        jPanel7YourBowBooksUV.setLayout(jPanel7YourBowBooksUVLayout);
        jPanel7YourBowBooksUVLayout.setHorizontalGroup(
                jPanel7YourBowBooksUVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7YourBowBooksUVLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(jPanel7YourBowBooksUVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9YourBowBooksTitleUV, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                                        .addComponent(jLabel10YourBowBooksSubtitleUV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        jPanel7YourBowBooksUVLayout.setVerticalGroup(
                jPanel7YourBowBooksUVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7YourBowBooksUVLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9YourBowBooksTitleUV)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10YourBowBooksSubtitleUV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout jPanel4BooksOverviewUVLayout = new javax.swing.GroupLayout(jPanel4BooksOverviewUV);
        jPanel4BooksOverviewUV.setLayout(jPanel4BooksOverviewUVLayout);
        jPanel4BooksOverviewUVLayout.setHorizontalGroup(
                jPanel4BooksOverviewUVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4BooksOverviewUVLayout.createSequentialGroup()
                                .addContainerGap(258, Short.MAX_VALUE)
                                .addComponent(jPanel5AllBooksUV, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                                .addComponent(jPanel6AvBooksUV, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                                .addComponent(jPanel7YourBowBooksUV, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                .addContainerGap(259, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4BooksOverviewUVLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4TitleBooksOverviewUV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4BooksOverviewUVLayout.setVerticalGroup(
                jPanel4BooksOverviewUVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4BooksOverviewUVLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel4TitleBooksOverviewUV)
                                .addGap(30, 30, 30)
                                .addGroup(jPanel4BooksOverviewUVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jPanel5AllBooksUV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel6AvBooksUV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel7YourBowBooksUV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(43, 43, 43))
        );

        jLabel11SearchUV.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11SearchUV.setText("Search:");

        jTable1BooksOverviewUV.setModel(new javax.swing.table.DefaultTableModel());
        jScrollPaneBooksOverviewUV.setViewportView(jTable1BooksOverviewUV);

        javax.swing.GroupLayout jPanel8BooksOverviewTableUVLayout = new javax.swing.GroupLayout(jPanel8BooksOverviewTableUV);
        jPanel8BooksOverviewTableUV.setLayout(jPanel8BooksOverviewTableUVLayout);
        jPanel8BooksOverviewTableUVLayout.setHorizontalGroup(
                jPanel8BooksOverviewTableUVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8BooksOverviewTableUVLayout.createSequentialGroup()
                                .addContainerGap(102, Short.MAX_VALUE)
                                .addGroup(jPanel8BooksOverviewTableUVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jScrollPaneBooksOverviewUV, javax.swing.GroupLayout.DEFAULT_SIZE, 931, Short.MAX_VALUE)
                                        .addGroup(jPanel8BooksOverviewTableUVLayout.createSequentialGroup()
                                                .addComponent(jLabel11SearchUV)
                                                .addGap(46, 46, 46)
                                                .addComponent(jTextField1BooksOverviewSearchUV)))
                                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanel8BooksOverviewTableUVLayout.setVerticalGroup(
                jPanel8BooksOverviewTableUVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel8BooksOverviewTableUVLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(jPanel8BooksOverviewTableUVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextField1BooksOverviewSearchUV, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel11SearchUV))
                                .addGap(33, 33, 33)
                                .addComponent(jScrollPaneBooksOverviewUV, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3MainBooksOverviewUVLayout = new javax.swing.GroupLayout(jPanel3MainBooksOverviewUV);
        jPanel3MainBooksOverviewUV.setLayout(jPanel3MainBooksOverviewUVLayout);
        jPanel3MainBooksOverviewUVLayout.setHorizontalGroup(
                jPanel3MainBooksOverviewUVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel4BooksOverviewUV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3MainBooksOverviewUVLayout.createSequentialGroup()
                                .addComponent(jPanel8BooksOverviewTableUV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        jPanel3MainBooksOverviewUVLayout.setVerticalGroup(
                jPanel3MainBooksOverviewUVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3MainBooksOverviewUVLayout.createSequentialGroup()
                                .addComponent(jPanel4BooksOverviewUV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)
                                .addComponent(jPanel8BooksOverviewTableUV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel12TitleYourBowBooksUV.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel12TitleYourBowBooksUV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12TitleYourBowBooksUV.setText("Your Borrowed Books");

        jLabel13SearchUV.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13SearchUV.setText("Search:");

        jTable2YourBowBooksUV.setModel(new javax.swing.table.DefaultTableModel());
        jScrollPaneYourBowBooksUV.setViewportView(jTable2YourBowBooksUV);

        javax.swing.GroupLayout jPanel10YourBowBooksTableUVLayout = new javax.swing.GroupLayout(jPanel10YourBowBooksTableUV);
        jPanel10YourBowBooksTableUV.setLayout(jPanel10YourBowBooksTableUVLayout);
        jPanel10YourBowBooksTableUVLayout.setHorizontalGroup(
                jPanel10YourBowBooksTableUVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10YourBowBooksTableUVLayout.createSequentialGroup()
                                .addContainerGap(103, Short.MAX_VALUE)
                                .addGroup(jPanel10YourBowBooksTableUVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jScrollPaneYourBowBooksUV)
                                        .addGroup(jPanel10YourBowBooksTableUVLayout.createSequentialGroup()
                                                .addComponent(jLabel13SearchUV)
                                                .addGap(46, 46, 46)
                                                .addComponent(jTextField2YourBowBooksSearchUV, javax.swing.GroupLayout.DEFAULT_SIZE, 821, Short.MAX_VALUE)))
                                .addContainerGap(104, Short.MAX_VALUE))
        );
        jPanel10YourBowBooksTableUVLayout.setVerticalGroup(
                jPanel10YourBowBooksTableUVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel10YourBowBooksTableUVLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(jPanel10YourBowBooksTableUVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextField2YourBowBooksSearchUV, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel13SearchUV))
                                .addGap(33, 33, 33)
                                .addComponent(jScrollPaneYourBowBooksUV, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
                                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel9MainYourBowBooksUVLayout = new javax.swing.GroupLayout(jPanel9MainYourBowBooksUV);
        jPanel9MainYourBowBooksUV.setLayout(jPanel9MainYourBowBooksUVLayout);
        jPanel9MainYourBowBooksUVLayout.setHorizontalGroup(
                jPanel9MainYourBowBooksUVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel9MainYourBowBooksUVLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel9MainYourBowBooksUVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel10YourBowBooksTableUV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel12TitleYourBowBooksUV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        jPanel9MainYourBowBooksUVLayout.setVerticalGroup(
                jPanel9MainYourBowBooksUVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel9MainYourBowBooksUVLayout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(jLabel12TitleYourBowBooksUV, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(jPanel10YourBowBooksTableUV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );

        jLayeredPane1.setLayer(jPanel3MainBooksOverviewUV, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jPanel9MainYourBowBooksUV, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
                jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 1154, Short.MAX_VALUE)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jPanel3MainBooksOverviewUV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addContainerGap()))
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jPanel9MainYourBowBooksUV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jLayeredPane1Layout.setVerticalGroup(
                jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 826, Short.MAX_VALUE)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jPanel3MainBooksOverviewUV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addContainerGap()))
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                                        .addComponent(jPanel9MainYourBowBooksUV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1MenubarUV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLayeredPane1)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1MenubarUV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLayeredPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1BookOverviewUVActionPerformed(java.awt.event.ActionEvent evt) {
        clearTableSelection();
        jPanel9MainYourBowBooksUV.setVisible(false);
        jPanel3MainBooksOverviewUV.setVisible(true);
    }

    private void jButton2BorrowBooksUVActionPerformed(java.awt.event.ActionEvent evt) {
        clearTableSelection();
        jPanel3MainBooksOverviewUV.setVisible(false);
        jPanel9MainYourBowBooksUV.setVisible(true);
    }

    private void jButton3LogoutUVActionPerformed(java.awt.event.ActionEvent evt) {
        this.dispose();
        new StandardView().setVisible(true);
    }

    private void addIcons() {
        jLabel2IconUV.setIcon(new javax.swing.ImageIcon(Objects.requireNonNull(getClass().getResource("/icons/LmsIcon.png"))));
    }

    private void setTableModels() {
        jTable1BooksOverviewUV.setAutoCreateRowSorter(true);
        jTable2YourBowBooksUV.setAutoCreateRowSorter(true);

        jTable1BooksOverviewUV.setRowHeight(60); // für cover

        // Verhindert multi selection
        jTable1BooksOverviewUV.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jTable2YourBowBooksUV.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        // Layout Werte
        String[] bookColumnNames = {"Cover", "Title", "Author", "Pages", "ISBN", "Location", "Availability"};
        String[] returnBookColumnNames = {"Title", "Author", "ISBN", "Username", "Borrowed on", "Due Date"};

        jTable1BooksOverviewUV.setModel(new javax.swing.table.DefaultTableModel(bookColumnNames, 0));
        jTable2YourBowBooksUV.setModel(new javax.swing.table.DefaultTableModel(returnBookColumnNames, 0));

        // Layout der Tabellen
        // Todo in eigene Klasse und dann checken von welcher Klasse die neue aufgerufen wird
        TableCellRenderer originalRenderer = jTable1BooksOverviewUV.getDefaultRenderer(Object.class);
        jTable1BooksOverviewUV.setDefaultRenderer(Object.class, new CellRenderer(originalRenderer));
        jTable1BooksOverviewUV.getColumnModel().getColumn(0).setCellRenderer(new ImageRenderer()); // Implementiert Book Cover
        jTable2YourBowBooksUV.setDefaultRenderer(Object.class, new CellRendererReturnBooks(originalRenderer)); // Return Books für DueDate
    }

    // Entfernt Auswahl der Table-Row
    private void clearTableSelection() {
        jTable1BooksOverviewUV.getSelectionModel().clearSelection();
        jTable2YourBowBooksUV.getSelectionModel().clearSelection();
    }

    private void updateBookOverviewAV() {
        objects.updateBookList();

        DefaultTableModel modelBookOverview = (DefaultTableModel) jTable1BooksOverviewUV.getModel();
        modelBookOverview.setRowCount(0);

        for (Book book : objects.getBooks()) {
            String cover = book.getCoverLocation();
            String title = book.getTitle();
            String author = book.getAuthor();
            String pages = book.getPages();
            String isbn = book.getIsbn();
            String location = book.getLocation();
            String availability = book.getAvailability();

            Object[] data = {cover, title, author, pages, isbn, location, availability};
            modelBookOverview.addRow(data);
        }
    }

    private void updateReturnBooksAV() {
        objects.updateBorrowedBookList();

        DefaultTableModel modelReturnBooksOverview = (DefaultTableModel) jTable2YourBowBooksUV.getModel();
        modelReturnBooksOverview.setRowCount(0);

        for (BorrowedBooks borrowedBooks : objects.getBorrowedBooks()) {
            String title = "";
            String author = "";

            String isbn = borrowedBooks.getIsbn();
            String username = borrowedBooks.getUsername();
            String borrowDate = borrowedBooks.getBorrowDate();
            String dueDate = borrowedBooks.getDueDate();

            // Check ob gleicher username
            if (username.equals(jLabel3SubtitleUV.getText())) {
                for (Book book : objects.getBooks()) {
                    if (book.getIsbn().equals(isbn)) {
                        title = book.getTitle();
                        author = book.getAuthor();
                    }
                }

                Object[] data = {title, author, isbn, username, borrowDate, dueDate};
                modelReturnBooksOverview.addRow(data);
            }
        }
    }

    private void updateStatistics() {
        analytics.getAnalytics(jLabel3SubtitleUV.getText());
        jLabel6AllBooksSubtitleUV.setText(Integer.toString(analytics.getBookAmount()));
        jLabel8AvBooksSubtitleUV.setText(Integer.toString(analytics.getAvailableBooks()));
        jLabel10YourBowBooksSubtitleUV.setText(Integer.toString(analytics.getUserAmountBorrowedBooks()));
    }

    private void addTableListener() {
        jTextField1BooksOverviewSearchUV.getDocument().addDocumentListener(
                new DocumentListener() {
                    @Override
                    public void insertUpdate(DocumentEvent e) {
                        searchBooksOverviewTable(jTextField1BooksOverviewSearchUV.getText());
                    }

                    @Override
                    public void removeUpdate(DocumentEvent e) {
                        searchBooksOverviewTable(jTextField1BooksOverviewSearchUV.getText());
                    }

                    @Override
                    public void changedUpdate(DocumentEvent e) {
                        searchBooksOverviewTable(jTextField1BooksOverviewSearchUV.getText());
                    }
                }
        );
        jTextField2YourBowBooksSearchUV.getDocument().addDocumentListener(
                new DocumentListener() {
                    @Override
                    public void insertUpdate(DocumentEvent e) {
                        searchYourBowBooksTable(jTextField2YourBowBooksSearchUV.getText());
                    }

                    @Override
                    public void removeUpdate(DocumentEvent e) {
                        searchYourBowBooksTable(jTextField2YourBowBooksSearchUV.getText());
                    }

                    @Override
                    public void changedUpdate(DocumentEvent e) {
                        searchYourBowBooksTable(jTextField2YourBowBooksSearchUV.getText());
                    }
                }
        );
    }

    private void searchBooksOverviewTable(String input) {
        DefaultTableModel currTableModelBooksOverview = (DefaultTableModel) jTable1BooksOverviewUV.getModel();
        currTableModelBooksOverview.setRowCount(0); // Table wird geleert

        for (Book book : objects.getBooks()) {
            String cover = book.getCoverLocation();
            String title = book.getTitle();
            String author = book.getAuthor();
            String pages = book.getPages();
            String isbn = book.getIsbn();
            String location = book.getLocation();
            String availability = book.getAvailability();

            if (title.contains(input) || author.contains(input) || pages.contains(input) || isbn.contains(input) || location.contains(input)) {
                Object[] row = {cover, title, author, pages, isbn, location, availability};
                currTableModelBooksOverview.addRow(row);
            }
        }
    }

    private void searchYourBowBooksTable(String input) {
        DefaultTableModel currTableModel = (DefaultTableModel) jTable2YourBowBooksUV.getModel();
        currTableModel.setRowCount(0);

        for (BorrowedBooks borrowedBooks : objects.getBorrowedBooks()) {
            String title = "";
            String author = "";
            String isbn = borrowedBooks.getIsbn();
            String username = borrowedBooks.getUsername();
            String borrowDate = borrowedBooks.getBorrowDate();
            String dueDate = borrowedBooks.getDueDate();

            // Check ob gleicher username
            if (username.equals(jLabel3SubtitleUV.getText())) {
                for (Book book : objects.getBooks()) {
                    if (book.getIsbn().equals(isbn)) {
                        title = book.getTitle();
                        author = book.getAuthor();
                    }
                }

                if (title.contains(input) || author.contains(input) || username.contains(input) || borrowDate.contains(input) || dueDate.contains(input)) {
                    Object[] row = {title, author, username, isbn, borrowDate, dueDate};
                    currTableModel.addRow(row);
                }
            }
        }
    }

    private void addNimbusLook() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException |
                 UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1BookOverviewUV;
    private javax.swing.JButton jButton2BorrowBooksUV;
    private javax.swing.JButton jButton3LogoutUV;
    private javax.swing.JLabel jLabel10YourBowBooksSubtitleUV;
    private javax.swing.JLabel jLabel11SearchUV;
    private javax.swing.JLabel jLabel12TitleYourBowBooksUV;
    private javax.swing.JLabel jLabel13SearchUV;
    private javax.swing.JLabel jLabel1TitleUV;
    private javax.swing.JLabel jLabel2IconUV;
    private javax.swing.JLabel jLabel3SubtitleUV;
    private javax.swing.JLabel jLabel4TitleBooksOverviewUV;
    private javax.swing.JLabel jLabel5AllBooksTitleUV;
    private javax.swing.JLabel jLabel6AllBooksSubtitleUV;
    private javax.swing.JLabel jLabel7AvBooksTitleUV;
    private javax.swing.JLabel jLabel8AvBooksSubtitleUV;
    private javax.swing.JLabel jLabel9YourBowBooksTitleUV;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel10YourBowBooksTableUV;
    private javax.swing.JPanel jPanel1MenubarUV;
    private javax.swing.JPanel jPanel2TitleBlockUV;
    private javax.swing.JPanel jPanel3MainBooksOverviewUV;
    private javax.swing.JPanel jPanel4BooksOverviewUV;
    private javax.swing.JPanel jPanel5AllBooksUV;
    private javax.swing.JPanel jPanel6AvBooksUV;
    private javax.swing.JPanel jPanel7YourBowBooksUV;
    private javax.swing.JPanel jPanel8BooksOverviewTableUV;
    private javax.swing.JPanel jPanel9MainYourBowBooksUV;
    private javax.swing.JScrollPane jScrollPaneBooksOverviewUV;
    private javax.swing.JScrollPane jScrollPaneYourBowBooksUV;
    private javax.swing.JTable jTable1BooksOverviewUV;
    private javax.swing.JTable jTable2YourBowBooksUV;
    private javax.swing.JTextField jTextField1BooksOverviewSearchUV;
    private javax.swing.JTextField jTextField2YourBowBooksSearchUV;
    // End of variables declaration//GEN-END:variables
}
