/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package net.is.lms.project.dialogs;

import net.is.lms.project.instances.Book;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;

import javax.imageio.ImageIO;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.*;
import java.nio.file.Files;
import java.util.regex.Pattern;

/**
 * @author dadi
 */
public class BookDialog extends javax.swing.JDialog {
    private String addBookString = "Add Book";
    private String editBookString = "Edit Book";

    private JSONArray jsonArray = new JSONArray();
    private File sourceFile = null;
    private File destinationFile = null;
    private File oldFile = null;

    /**
     * Creates new form BookDialog
     */
    public BookDialog(java.awt.Frame parent, boolean modal, boolean inputValue) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        addNimbusLook();

        jLabel1BookTitle.setText(inputValue ? addBookString : editBookString);
        setTitle(inputValue ? addBookString : editBookString);
    }

    public BookDialog(java.awt.Frame parent, boolean modal, boolean inputValue, Book book) {
        super(parent, modal);
        initComponents();
        addToTextField(book);
        setLocationRelativeTo(null);
        addNimbusLook();

        jLabel1BookTitle.setText(inputValue ? addBookString : editBookString);
        setTitle(inputValue ? addBookString : editBookString);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1MainBook = new javax.swing.JPanel();
        jLabel1BookTitle = new javax.swing.JLabel();
        jLabel2InsertTitle = new javax.swing.JLabel();
        jTextField1Title = new javax.swing.JTextField();
        jTextField2Author = new javax.swing.JTextField();
        jTextField3Pages = new javax.swing.JTextField();
        jTextField4Isbn = new javax.swing.JTextField();
        jTextField5Location = new javax.swing.JTextField();
        jLabel3InsertAuthor = new javax.swing.JLabel();
        jLabel4InsertPages = new javax.swing.JLabel();
        jLabel5InsertIsbn = new javax.swing.JLabel();
        jLabel6InsertLocation = new javax.swing.JLabel();
        jLabel6CoverPreviewTitle = new javax.swing.JLabel();
        jButton1UploadCover = new javax.swing.JButton();
        jButton2DeleteCover = new javax.swing.JButton();
        jButton3Save = new javax.swing.JButton();
        jButton4Cancel = new javax.swing.JButton();
        jLabel7CoverPreview = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1MainBook.setBackground(new java.awt.Color(203, 230, 255));

        jLabel1BookTitle.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1BookTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1BookTitle.setText("Add Book");

        jLabel2InsertTitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2InsertTitle.setText("Title");

        jTextField1Title.setPreferredSize(new java.awt.Dimension(284, 22));

        jTextField2Author.setPreferredSize(new java.awt.Dimension(284, 22));

        jTextField3Pages.setPreferredSize(new java.awt.Dimension(284, 22));

        jTextField4Isbn.setPreferredSize(new java.awt.Dimension(284, 22));

        jTextField5Location.setPreferredSize(new java.awt.Dimension(284, 22));

        jLabel3InsertAuthor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3InsertAuthor.setText("Author");

        jLabel4InsertPages.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4InsertPages.setText("Pages");

        jLabel5InsertIsbn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5InsertIsbn.setText("ISBN (10 digit number - not changeable)");

        jLabel6InsertLocation.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6InsertLocation.setText("Location (opt.)");

        jLabel6CoverPreviewTitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6CoverPreviewTitle.setText("Cover Preview");

        jButton1UploadCover.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1UploadCover.setText("Upload Cover");
        jButton1UploadCover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1UploadCoverActionPerformed(evt);
            }
        });

        jButton2DeleteCover.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2DeleteCover.setText("Delete Cover");
        jButton2DeleteCover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2DeleteCoverActionPerformed(evt);
            }
        });

        jButton3Save.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton3Save.setText("Save");
        jButton3Save.setPreferredSize(new java.awt.Dimension(96, 31));
        jButton3Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3SaveActionPerformed(evt);
            }
        });

        jButton4Cancel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton4Cancel.setText("Cancel");
        jButton4Cancel.setPreferredSize(new java.awt.Dimension(96, 31));
        jButton4Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4CancelActionPerformed(evt);
            }
        });

        jLabel7CoverPreview.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7CoverPreview.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel7CoverPreview.setOpaque(true);

        javax.swing.GroupLayout jPanel1MainBookLayout = new javax.swing.GroupLayout(jPanel1MainBook);
        jPanel1MainBook.setLayout(jPanel1MainBookLayout);
        jPanel1MainBookLayout.setHorizontalGroup(
                jPanel1MainBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1MainBookLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1BookTitle)
                                .addGap(84, 84, 84))
                        .addGroup(jPanel1MainBookLayout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(jPanel1MainBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1MainBookLayout.createSequentialGroup()
                                                .addComponent(jLabel3InsertAuthor)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel1MainBookLayout.createSequentialGroup()
                                                .addGroup(jPanel1MainBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1MainBookLayout.createSequentialGroup()
                                                                .addComponent(jLabel2InsertTitle)
                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                        .addComponent(jTextField1Title, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jTextField2Author, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jTextField4Isbn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jTextField5Location, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jTextField3Pages, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(jPanel1MainBookLayout.createSequentialGroup()
                                                                .addGroup(jPanel1MainBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jButton3Save, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel7CoverPreview, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addGroup(jPanel1MainBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(jButton1UploadCover, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jButton2DeleteCover, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jButton4Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addContainerGap(56, Short.MAX_VALUE))
                                        .addGroup(jPanel1MainBookLayout.createSequentialGroup()
                                                .addGroup(jPanel1MainBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel6InsertLocation)
                                                        .addComponent(jLabel5InsertIsbn)
                                                        .addComponent(jLabel4InsertPages))
                                                .addGap(0, 0, Short.MAX_VALUE))))
                        .addGroup(jPanel1MainBookLayout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(jLabel6CoverPreviewTitle)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1MainBookLayout.setVerticalGroup(
                jPanel1MainBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1MainBookLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel1BookTitle)
                                .addGap(15, 15, 15)
                                .addComponent(jLabel2InsertTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(19, 19, 19)
                                .addComponent(jLabel3InsertAuthor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField2Author, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(19, 19, 19)
                                .addComponent(jLabel4InsertPages)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField3Pages, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(19, 19, 19)
                                .addComponent(jLabel5InsertIsbn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField4Isbn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(19, 19, 19)
                                .addComponent(jLabel6InsertLocation)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField5Location, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                                .addGroup(jPanel1MainBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1MainBookLayout.createSequentialGroup()
                                                .addGap(63, 63, 63)
                                                .addComponent(jButton1UploadCover, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButton2DeleteCover, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1MainBookLayout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addComponent(jLabel6CoverPreviewTitle)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel7CoverPreview, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1MainBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton4Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton3Save, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1MainBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1MainBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1UploadCoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1UploadCoverActionPerformed
        BufferedImage originalImg = null;

        // Popup für die Bildauswahl
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("JPG & PNG Images", "jpg", "png");
        fileChooser.setFileFilter(filter);

        int result = fileChooser.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            sourceFile = fileChooser.getSelectedFile();
            try {
                originalImg = ImageIO.read(sourceFile);
                destinationFile = new File("src/main/resources/cover/" + sourceFile.getName());
            } catch (Exception e) {
                e.printStackTrace();
            }
            ImageIcon newImg = new ImageIcon(originalImg.getScaledInstance(jLabel7CoverPreview.getWidth(), jLabel7CoverPreview.getHeight(), java.awt.Image.SCALE_SMOOTH));

            jLabel7CoverPreview.setIcon(newImg);
        }
    }//GEN-LAST:event_jButton1UploadCoverActionPerformed

    private void jButton2DeleteCoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2DeleteCoverActionPerformed
        if (destinationFile != null) {
            jLabel7CoverPreview.setIcon(new ImageIcon());
            destinationFile = null;
            sourceFile = null;
        }
    }//GEN-LAST:event_jButton2DeleteCoverActionPerformed

    private void jButton3SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3SaveActionPerformed
        if (!jTextField1Title.getText().equals("") && !jTextField2Author.getText().equals("") && !jTextField3Pages.getText().equals("") && !jTextField4Isbn.getText().equals("")) {
            if (!Pattern.matches("[A-Za-z]+", jTextField2Author.getText())) {
                JOptionPane.showMessageDialog(this, "The author should only contain letters!", "Error!", JOptionPane.ERROR_MESSAGE);
            } else if (!Pattern.matches("\\d{10}", jTextField4Isbn.getText())) {
                JOptionPane.showMessageDialog(this, "The ISBN has to be a 10 digit number!", "Error!", JOptionPane.ERROR_MESSAGE);
            } else if (!Pattern.matches("^[1-9]\\d*$", jTextField3Pages.getText())) {
                JOptionPane.showMessageDialog(this, "Only numbers higher than 0 are allowed for pages!", "Error!", JOptionPane.ERROR_MESSAGE);
            } else {
                readFile();

                if (jLabel1BookTitle.getText().equals("Add Book")) {
//                    System.out.println("Add Book?");
                    addBookToSystem();
                }
                if (jLabel1BookTitle.getText().equals("Edit Book")) {
                    editBook();
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please fill out all text fields!", "Error!", JOptionPane.ERROR_MESSAGE);
        }
    }
//GEN-LAST:event_jButton3SaveActionPerformed

    private void jButton4CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4CancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton4CancelActionPerformed

    private void addBookToSystem() {
        boolean isbnAlreadyExists = false;
        for (int i = 0; i < jsonArray.size(); i++) {
            JSONObject jsonObject = (JSONObject) jsonArray.get(i);
            Object book = jsonObject.get("Book");
            JSONObject bookObj = (JSONObject) book;
            if (bookObj.get("ISBN").toString().equals(jTextField4Isbn.getText())) {
                JOptionPane.showMessageDialog(this, "This ISBN already exists!", "Error!", JOptionPane.ERROR_MESSAGE);
                isbnAlreadyExists = true;
                break;
            }
        }
        if (!isbnAlreadyExists) {
            JSONObject jsonObject = new JSONObject();
            if (destinationFile != null) {
                jsonObject.put("Cover", "" + destinationFile.toPath() + "");
            } else {
                jsonObject.put("Cover", "X");
            }

            jsonObject.put("Title", jTextField1Title.getText());
            jsonObject.put("Author", jTextField2Author.getText());
            jsonObject.put("Pages", jTextField3Pages.getText());
            jsonObject.put("ISBN", jTextField4Isbn.getText());
            jsonObject.put("Location", jTextField5Location.getText());
            jsonObject.put("Availability", "Available"); // Beim Hinzufügen ist es immer Available, bei Edit wird dann getAvailability verwendet
            JSONObject bookObj = new JSONObject();
            bookObj.put("Book", jsonObject);
            jsonArray.add(bookObj);
            try {
                if (sourceFile != null && destinationFile != null) {
                    Files.copy(sourceFile.toPath(), destinationFile.toPath());
                }
                writeFile();
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "This icon already exists!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void editBook() {
        for (int i = 0; i < jsonArray.size(); i++) {
            JSONObject jsonObject = (JSONObject) jsonArray.get(i);
            Object book = jsonObject.get("Book");
            JSONObject bookObj = (JSONObject) book;
            if (bookObj.get("ISBN").toString().equals(jTextField4Isbn.getText())) {
                if (destinationFile != null) {
                    bookObj.put("Cover", "" + destinationFile.toPath() + "");
                    if (oldFile != null) {
                        if (!oldFile.getPath().equals(destinationFile.getPath())) {
                            oldFile.delete();
                        }
                    }
                } else {
                    bookObj.put("Cover", "X");
                    if (oldFile != null) {
                        oldFile.delete();
                    }
                }
                bookObj.put("Title", jTextField1Title.getText());
                bookObj.put("Author", jTextField2Author.getText());
                bookObj.put("Pages", jTextField3Pages.getText());
                bookObj.put("ISBN", jTextField4Isbn.getText());
                bookObj.put("Location", jTextField5Location.getText());
                jsonObject.put("Book", bookObj);

                try {
                    if (sourceFile != null && destinationFile != null) {
                        Files.copy(sourceFile.toPath(), destinationFile.toPath());
                    }
                    writeFile();
                } catch (IOException e) {
                    JOptionPane.showMessageDialog(this, "This icon already exists!", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }

    private void addToTextField(Book book) {
        if (!book.getCoverLocation().equals("X")) {
            destinationFile = new File(book.getCoverLocation());
            oldFile = new File(book.getCoverLocation());
            ImageIcon icon = new ImageIcon(book.getCoverLocation());
            Image image = icon.getImage(); // transform it
            Image newImg = image.getScaledInstance(jLabel7CoverPreview.getWidth(), jLabel7CoverPreview.getHeight(), java.awt.Image.SCALE_SMOOTH); // scale it the smooth way
            icon = new ImageIcon(newImg);
            jLabel7CoverPreview.setIcon(icon);
        }
        jTextField1Title.setText(book.getTitle());
        jTextField2Author.setText(book.getAuthor());
        jTextField3Pages.setText(book.getPages());
        jTextField4Isbn.setText(book.getIsbn());
        jTextField4Isbn.setEnabled(false);
        jTextField5Location.setText(book.getLocation());

        if (book.getLocation().equals("-/-")) jTextField3Pages.setText("");
    }

    private void readFile() {
        File file = new File("src/main/resources/books.txt");
        if (file.length() != 0) {
            JSONParser jsonParser = new JSONParser();
            try (FileReader fileReader = new FileReader("src/main/resources/books.txt")) {
                Object obj = jsonParser.parse(fileReader);
                jsonArray = (JSONArray) obj;
            } catch (ParseException | IOException e) {
                e.printStackTrace();
            }
        }
    }

    private void writeFile() {
        try (FileWriter fileWriter = new FileWriter("src/main/resources/books.txt")) {
            fileWriter.write(jsonArray.toJSONString());
        } catch (IOException e) {
            e.printStackTrace();
        }
        this.dispose();
    }

    private void addNimbusLook() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException |
                 UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1UploadCover;
    private javax.swing.JButton jButton2DeleteCover;
    private javax.swing.JButton jButton3Save;
    private javax.swing.JButton jButton4Cancel;
    private javax.swing.JLabel jLabel1BookTitle;
    private javax.swing.JLabel jLabel2InsertTitle;
    private javax.swing.JLabel jLabel3InsertAuthor;
    private javax.swing.JLabel jLabel4InsertPages;
    private javax.swing.JLabel jLabel5InsertIsbn;
    private javax.swing.JLabel jLabel6CoverPreviewTitle;
    private javax.swing.JLabel jLabel6InsertLocation;
    private javax.swing.JLabel jLabel7CoverPreview;
    private javax.swing.JPanel jPanel1MainBook;
    private javax.swing.JTextField jTextField1Title;
    private javax.swing.JTextField jTextField2Author;
    private javax.swing.JTextField jTextField3Pages;
    private javax.swing.JTextField jTextField4Isbn;
    private javax.swing.JTextField jTextField5Location;
    // End of variables declaration//GEN-END:variables
}
