/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package net.is.lms.project.dialogs;

import net.is.lms.project.instances.User;
import net.is.lms.project.frames.FetchObjects;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;

/**
 * @author dadi
 */
public class BorrowBookDialog extends javax.swing.JDialog {
    private final FetchObjects objects = new FetchObjects();
    private final String isbn;
    private JSONArray jsonArray = new JSONArray();
    private JSONArray jsonArrayBooks = new JSONArray();

    /**
     * Creates new form BorrowBookDialog
     */
    public BorrowBookDialog(java.awt.Frame parent, boolean modal, String isbn) {
        super(parent, modal);
        this.isbn = isbn;
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Borrow Book " + isbn);
        addNimbusLook();

        objects.updateUserList();
        fetchTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1MainBorrowBook = new javax.swing.JPanel();
        jLabel1BorrowBookTitle = new javax.swing.JLabel();
        jPanel2BorrowBookTable = new javax.swing.JPanel();
        jLabel2Search = new javax.swing.JLabel();
        jTextField1BorrowBookSearch = new javax.swing.JTextField();
        jScrollPaneBorrowBook = new javax.swing.JScrollPane();
        jTable1UserOverview = new javax.swing.JTable() {
            public boolean editCellAt(int row, int column, java.util.EventObject e) {
                return false;
            }
        };
        jButton1Save = new javax.swing.JButton();
        jButton2Cancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1MainBorrowBook.setBackground(new java.awt.Color(203, 230, 255));

        jLabel1BorrowBookTitle.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1BorrowBookTitle.setText("Borrow Book to User");

        jPanel2BorrowBookTable.setBackground(new java.awt.Color(203, 230, 255));

        jLabel2Search.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2Search.setText("Search:");

        jTable1UserOverview.setModel(new javax.swing.table.DefaultTableModel());
        jScrollPaneBorrowBook.setViewportView(jTable1UserOverview);

        jButton1Save.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1Save.setText("OK");
        jButton1Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1SaveActionPerformed(evt);
            }
        });

        jButton2Cancel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2Cancel.setText("Cancel");
        jButton2Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2CancelActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Assign the book to a user:");

        javax.swing.GroupLayout jPanel2BorrowBookTableLayout = new javax.swing.GroupLayout(jPanel2BorrowBookTable);
        jPanel2BorrowBookTable.setLayout(jPanel2BorrowBookTableLayout);
        jPanel2BorrowBookTableLayout.setHorizontalGroup(
                jPanel2BorrowBookTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2BorrowBookTableLayout.createSequentialGroup()
                                .addGap(149, 149, 149)
                                .addComponent(jButton1Save, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(149, 149, 149))
                        .addGroup(jPanel2BorrowBookTableLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPanel2BorrowBookTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addGroup(jPanel2BorrowBookTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(jPanel2BorrowBookTableLayout.createSequentialGroup()
                                                        .addComponent(jLabel2Search)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jTextField1BorrowBookSearch))
                                                .addComponent(jScrollPaneBorrowBook, javax.swing.GroupLayout.PREFERRED_SIZE, 843, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(26, 26, 26))
        );
        jPanel2BorrowBookTableLayout.setVerticalGroup(
                jPanel2BorrowBookTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2BorrowBookTableLayout.createSequentialGroup()
                                .addContainerGap(35, Short.MAX_VALUE)
                                .addGroup(jPanel2BorrowBookTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2Search)
                                        .addComponent(jTextField1BorrowBookSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPaneBorrowBook, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addGroup(jPanel2BorrowBookTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton1Save)
                                        .addComponent(jButton2Cancel))
                                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout jPanel1MainBorrowBookLayout = new javax.swing.GroupLayout(jPanel1MainBorrowBook);
        jPanel1MainBorrowBook.setLayout(jPanel1MainBorrowBookLayout);
        jPanel1MainBorrowBookLayout.setHorizontalGroup(
                jPanel1MainBorrowBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1MainBorrowBookLayout.createSequentialGroup()
                                .addGap(220, 220, 220)
                                .addComponent(jLabel1BorrowBookTitle)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jPanel2BorrowBookTable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1MainBorrowBookLayout.setVerticalGroup(
                jPanel1MainBorrowBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1MainBorrowBookLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1BorrowBookTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2BorrowBookTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1MainBorrowBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1MainBorrowBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1SaveActionPerformed
        try {
            int rowNumber = jTable1UserOverview.getSelectedRow(); // Holt Nummer der ausgewählten Reihe

            if (rowNumber >= 0) {   // Check ob Reihe ausgewählt ist
//                int ID = (int) table.getValueAt(rowNumber, 0); // Holt sich die ID für Ausgabe
                String username = (String) jTable1UserOverview.getValueAt(rowNumber, 2);
                if (JOptionPane.showConfirmDialog(null, "Do you really want to borrow the selected book to" + username + "?", "Are you sure?", JOptionPane.OK_CANCEL_OPTION) == 0) { // ConfirmPane
                    borrowBookToUser(username);
                    changeStatus();
                    this.dispose();
                }
            } else { // Fehlermessage
                JOptionPane.showMessageDialog(this, "Please select the line of a user", "Warning!", JOptionPane.WARNING_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Unexpected error, please try again", "Error", JOptionPane.ERROR_MESSAGE);
            System.out.println("Error whilst clicking deleteBook: " + ex.getMessage());
        }
    }//GEN-LAST:event_jButton1SaveActionPerformed

    private void jButton2CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2CancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2CancelActionPerformed

    private void fetchTable() {
        String[] userColumnNames = {"First Name", "Last Name", "Username", "Email", "Phonenumber"};
        jTable1UserOverview.setModel(new javax.swing.table.DefaultTableModel(userColumnNames, 0));

        jTable1UserOverview.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        DefaultTableModel modelUserOverview = (DefaultTableModel) jTable1UserOverview.getModel();
        modelUserOverview.setRowCount(0);

        for (User user : objects.getUsers()) {
            String firstName = user.getFirstName();
            String lastName = user.getLastName();
            String userName = user.getUsername();
            String email = user.getEmail();
            String phoneNumber = user.getPhoneNumber();

            Object[] data = {firstName, lastName, userName, email, phoneNumber};
            modelUserOverview.addRow(data);
        }
    }


    private void borrowBookToUser(String username) {
        DateFormat dtf = new SimpleDateFormat("dd/MM/yyyy");
        Date currentDate = new Date();
        Calendar c = Calendar.getInstance();
        c.setTime(currentDate);
        c.add(Calendar.MONTH, 1); // Genau ein Monat in die Zukunft vom heutigen Datum
        Date currentDateDeadline = c.getTime();

        JSONObject jsonObject = new JSONObject();
        JSONParser jsonParser = new JSONParser();
        File file = new File("src/main/resources/borrowedbooks.txt");
        if (file.length() != 0) {
            try (FileReader fileReader = new FileReader("src/main/resources/borrowedbooks.txt")) {
                Object obj = jsonParser.parse(fileReader);
                jsonArray = (JSONArray) obj;
            } catch (ParseException | IOException e) {
                e.printStackTrace();
            }
        }

        jsonObject.put("Username", username);
        jsonObject.put("ISBN", isbn);
        jsonObject.put("BorrowDate", dtf.format(currentDate));
        jsonObject.put("DueDate", dtf.format(currentDateDeadline));


        JSONObject bookObj = new JSONObject();
        bookObj.put("BorrowedBook", jsonObject);
        jsonArray.add(bookObj);

        try (FileWriter fileWriter = new FileWriter("src/main/resources/borrowedbooks.txt")) {
            fileWriter.write(jsonArray.toJSONString());
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    private void changeStatus() {
        File file = new File("src/main/resources/books.txt");
        if (file.length() != 0) {
            JSONParser jsonParser = new JSONParser();
            try (FileReader fileReader = new FileReader("src/main/resources/books.txt")) {
                Object obj = jsonParser.parse(fileReader);
                jsonArrayBooks = (JSONArray) obj;
            } catch (ParseException | IOException e) {
                e.printStackTrace();
            }
        }

        for (int i = 0; i < jsonArrayBooks.size(); i++) {
            JSONObject jsonObject = (JSONObject) jsonArrayBooks.get(i);
            Object book = jsonObject.get("Book");
            JSONObject bookObj = (JSONObject) book;
            if (bookObj.get("ISBN").toString().equals(isbn)) {
                bookObj.put("Availability", "Borrowed");
                jsonObject.put("Book", bookObj);
                break;
            }
        }

        try (FileWriter fileWriter = new FileWriter("src/main/resources/books.txt")) {
            fileWriter.write(jsonArrayBooks.toJSONString());
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    private void addNimbusLook() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException |
                 UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BorrowBookDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Save;
    private javax.swing.JButton jButton2Cancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1BorrowBookTitle;
    private javax.swing.JLabel jLabel2Search;
    private javax.swing.JPanel jPanel1MainBorrowBook;
    private javax.swing.JPanel jPanel2BorrowBookTable;
    private javax.swing.JScrollPane jScrollPaneBorrowBook;
    private javax.swing.JTable jTable1UserOverview;
    private javax.swing.JTextField jTextField1BorrowBookSearch;
    // End of variables declaration//GEN-END:variables
}
